version: "0.0.4"

starting-balance: 0
currency-singular: "Bit"
currency-plural: "Bits"
pay-distance-max: 25

money-drop-worlds:
  pveworld:
    enabled: true
    drop-chance: 0.25
    multiplier-per-100-blocks: 1.0
    exponential-bonus: 1.1

bit-bomb-chance: 0.02
lucky-bit-bomb-chance: 0.04

no-loss-worlds:
- pvpworld
- weenieland
- mcworldforbabies

database:
  enabled: true
  host: localhost
  port: 3306
  username: localuser
  password: localpassword
  database: localdb